Werkt niet meer

# /netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"   # pin Node 22 voor consistente builds

# Voor SPA routing (optioneel):
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200

# Als je Netlify Functions gebruikt (optioneel):
# [functions]
#   directory = "netlify/functions"
